disintegrate-es/disintegrate

- Cargo.lock
- README.md
- disintegrate-macros/Cargo.toml
- disintegrate-postgres/Cargo.toml
- disintegrate-postgres/src/event_store/insert_builder.rs
- disintegrate-postgres/src/event_store/tests/event_store.rs
- disintegrate-postgres/src/event_store/tests/state_store.rs
- disintegrate-postgres/src/listener/tests.rs
- disintegrate/Cargo.toml
- disintegrate/src/stream_query.rs
- examples/banking/Cargo.toml
- examples/banking/src/domain.rs
- examples/cart/Cargo.toml
- examples/cart/src/cart.rs
- examples/courses/Cargo.toml
- examples/courses/src/domain/course.rs
- examples/courses/src/domain/student.rs
- examples/courses/src/domain/subscription.rs
- examples/courses/src/domain/unsubscription.rs
- examples/courses/tests/subscriptions_concurrency_test.js
This PR allows us to remove unnecessary clone calls on the identifiers values in the query macro.
> Identifiers values as ref

- disintegrate-postgres/src/event_store.rs
- disintegrate-postgres/src/event_store/query_builder.rs
This PR fixes a bug that occurs when a decision writes a set of events that it doesn't read. Without this fix, the events are written into the event store but remain unconsumed, allowing another decision to commit even if it hasn't read those events.
> Fix concurrent writes

- Cargo.lock
- README.md
- disintegrate-macros/Cargo.toml
- disintegrate-macros/src/event.rs
- disintegrate-macros/src/state_query.rs
- disintegrate-postgres/Cargo.toml
- disintegrate/Cargo.toml
- disintegrate/src/stream_query.rs
- disintegrate/src/utils.rs
- examples/banking/Cargo.toml
- examples/cart/Cargo.toml
- examples/cart/src/event.rs
- examples/courses/Cargo.toml
> Improve errors

- disintegrate-macros/src/event.rs
- disintegrate-macros/src/state_query.rs
- disintegrate-macros/tests/event.rs
- disintegrate-postgres/src/event_store/tests.rs
This PR allows users to box events in an unnamed enum variant.
> Add support to boxed events

- Cargo.lock
- examples/courses/Cargo.toml
- examples/courses/src/application/commands.rs
- examples/courses/src/application/queries.rs
- examples/courses/src/domain/course.rs
- examples/courses/src/domain/student.rs
- examples/courses/src/domain/subscription.rs
- examples/courses/src/domain/unsubscription.rs
- examples/courses/src/main.rs
This PR replaces `println` with tracing `instrument`.
> Add tracing to courses example

- examples/courses/src/read_model.rs
This PR shows how to add a double delivery check of events. The `EventListener` ensures at-least-one delivery.  However, to prevent the read model from processing an event twice, it must first check if the event has been processed already. 
To show how to implement such a check, this PR adds it to the `Courses` read model. The check verifies whether the `event_id` of the received event is greater than the ones that have already been processed.
> Add event listener double delivery check in the Courses example

- docs/docusaurus.config.js
> fix docusaurus config

- README.md
> Add readme docs bagde

- Cargo.lock
- disintegrate-macros/src/lib.rs
- disintegrate-postgres/src/listener.rs
- disintegrate/Cargo.toml
- disintegrate/src/decision.rs
- disintegrate/src/decision/state.rs
- disintegrate/src/decision/state_store.rs
- disintegrate/src/stream_query.rs
This PR adds tokio test for async tests.
> Add Tokio Test

- Cargo.lock
- README.md
- disintegrate-macros/Cargo.toml
- disintegrate-postgres/Cargo.toml
- disintegrate-serde/Cargo.toml
- disintegrate/Cargo.toml
- examples/banking/Cargo.toml
- examples/cart/Cargo.toml
- examples/courses/Cargo.toml
This PR bumps the disintegrate version from 0.8.0 to 1.0.0.
> Bump version to 1.0.0

- examples/courses/src/read_model.rs
This PR fixes the courses read model example rename update.
> Fix courses read model

- disintegrate-postgres/src/listener.rs
This PR allows to stop an `PgEventListener` when a shutdown is requested.
> Stop event listener when a shutdown occurres.

- disintegrate-postgres/src/event_store.rs
- disintegrate-postgres/src/lib.rs
- disintegrate-postgres/src/listener.rs
- disintegrate-postgres/src/listener/id_indexer.rs
- disintegrate/src/decision.rs
- docs/docs/postgres.md
This PR adds the Id Indexer, an utility to populate a new id in all the old events.
> Add Id Indexer

- disintegrate-macros/Cargo.toml
- disintegrate-postgres/Cargo.toml
- disintegrate-postgres/src/listener.rs
- disintegrate-postgres/src/listener/id_indexer.rs
- disintegrate-serde/Cargo.toml
- disintegrate-serde/src/serde/avro.rs
- disintegrate/Cargo.toml
This PR fixes the visibility of feature-gated documentation
> Show feature gated docs

- disintegrate-postgres/src/listener.rs
fix corresponding to patch documented in proposed solution to issue-161, which I raised. Interested in feedback and/or comments. Thanks!
> issue-161: add Send + Sync requirement to PgEventListener.executors

- disintegrate-postgres/src/error.rs
- disintegrate-postgres/src/event_store.rs
- disintegrate-postgres/src/event_store/append.rs
- disintegrate-postgres/src/event_store/query.rs
- disintegrate-postgres/src/event_store/sql/fn_event_store_begin_epoch.sql
- disintegrate-postgres/src/event_store/sql/fn_event_store_current_epoch.sql
- disintegrate-postgres/src/event_store/tests.rs
- disintegrate-postgres/src/listener/tests.rs
This PR fixes the event stream for highly concurrent environments.
> fix: events stream for highly concurrent environments

- Cargo.lock
- disintegrate-serde/Cargo.toml
- disintegrate-serde/src/serde.rs
- disintegrate-serde/src/serde/messagepack.rs
I basically took disintegrate-serde's json.rs  and adapted it to rmp_serde. The test passed.
> Add MessagePack support for serialisation and deserialisation

- docs/docs/developer_journey/handle_concurrency_conflicts.md
Small change in sample code in documentation - Update for V2 api comptiability.
> Documentation update concurrency page 

- docs/docs/faq.md
Added FAQ page in documentation.
> Added FAQ Page under documentation

- docs/docs/event_listeners.md
- EventListener & PersistedEvent needs Identifier type
- query!(DomainEvent) needs type
- Tip for actix-web
> Event listener doc updates
